name: Test teleop_tools
on:
  pull_request:
  push:
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '17 8 * * *'

jobs:
  ci:
    name: Foxy source job
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
      - uses: ros-tooling/setup-ros@v0.1
      - uses: ros-tooling/action-ros-ci@v0.1
        with:
          target-ros2-distro: foxy
          # build all packages listed in the meta package
          package-name:
            joy_teleop
            key_teleop
            mouse_teleop
            teleop_tools
            teleop_tools_msgs
